### ISSUE TITLE
Composer require error

### ISSUE THREAD

**Issue by fxcosta** [bndr/imgur-php-wrapper#9]
Hello! Composer require shows a error: 
[InvalidArgumentException]                                                   
Could not find package bndr/imgur-php-wrapper at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Check if you have missed something in submit package for packagist.

**Comment by bndr** [comment]
Can you try it now?

**Comment by fxcosta** [comment]
Now its works. Thanks!
